FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y git

COPY requirements-app.txt .

RUN pip install -r requirements-app.txt -t .

COPY slack_app.py .

# Command can be overwritten by providing a different command in the template directly.
CMD ["slack_app.handler"]
