FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y git

COPY requirements.txt .

RUN pip install -r requirements.txt -t .
RUN pip list

COPY app.py .

# Command can be overwritten by providing a different command in the template directly.
CMD ["app.handler"]
