AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

  Sample SAM Template for union rag
Resources:
  UnionRagFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 30
      MemorySize: 512
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        unionrag:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: post
      Environment:
        Variables:
          SLACK_BOT_TOKEN: <SLACK_BOT_TOKEN>
          SLACK_SIGNING_SECRET: <SLACK_SIGNING_SECRET>
    Metadata:
      Dockerfile: Dockerfile.awslambda
      DockerContext: .
      DockerTag: python3.11-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UnionRagApi:
    Description: "API Gateway endpoint URL for Prod stage for union rag function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UnionRagFunction:
    Description: "union rag Lambda Function ARN"
    Value: !GetAtt UnionRagFunction.Arn
  UnionRagFunctionIamRole:
    Description: "Implicit IAM Role created for union rag function"
    Value: !GetAtt UnionRagFunctionRole.Arn
